### Crear Reserva 1
POST http://localhost:3000/api/reservas
Content-Type: application/json

{
  "id_usuario": 1,
  "id_cancha": 2,
  "fecha": "2025-11-10",
  "hora_inicio": "15:00:00",
  "hora_fin": "17:00:00",
  "precio_total": 9000,
  "id_servicios": [1, 2]
}

### Obtener todas las reservas con servicios
GET http://localhost:3000/api/reservas


GET http://localhost:3000/api/reservas/rango-fecha?inicio=YYYY-MM-DD&fin=YYYY-MM-DD


### Obtener reserva por ID
GET http://localhost:3000/api/reservas/1

### Agregar nuevos servicios a una reserva existente
POST http://localhost:3000/api/reservas/1/servicios
Content-Type: application/json

{
  "id_servicios": [3]
}

### Eliminar un servicio de una reserva
DELETE http://localhost:3000/api/reservas/1/servicios/2

### Actualizar una reserva
PUT http://localhost:3000/api/reservas
Content-Type: application/json

{
  "id_reserva": 1,
  "fecha": "2025-11-12",
  "hora_inicio": "16:00:00",
  "hora_fin": "18:00:00",
  "precio_total": 9500
}

### Eliminar una reserva
DELETE http://localhost:3000/api/reservas/1/1/2
