## obtener todas las canchas


### Obtener todas las canchas
GET http://localhost:3000/api/canchas

### Crear nueva cancha
POST http://localhost:3000/api/canchas
Content-Type: application/json

{
    "id_cancha": 1,
    "nombre": "Cancha Futbol 5",
    "estado": "disponible"
}

### Modificar una cancha
PUT http://localhost:3000/api/canchas/2
Content-Type: application/json

{
    "nombre": "Cancha Modificadaa",
    "estado": "ocupada"
}

### Modificar una cancha
Patch http://localhost:3000/api/canchas/7
Content-Type: application/json

{
    "estado": "ocupada"
}


### delete una cancha
DELETE http://localhost:3000/api/canchas/8