### Obtener todas las localidades
GET http://localhost:3000/api/localidades

### Obtener una localidad por ID
GET http://localhost:3000/api/localidades/1

### Crear nueva localidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "Echesortu"
}

### Modificar una localidad
PATCH http://localhost:3000/api/localidades/1
Content-Type: application/json

{
    
    "nombre": "Puerto Norte"
}


### Eliminar una localidad
DELETE http://localhost:3000/api/localidades/4
